/**
 * H1 & Meta copy from PM_Structure_Keyword_H1_Meta_All_Courses_Added.xlsx
 * (H1 & Meta sheet, 70 rows). Keyed by Keyword Plan SEO URL.
 * Do not invent copy here — regenerate from the workbook.
 */

export type KeywordH1MetaRow = {
  source: string;
  primaryKeyword: string;
  h1: string;
  metaDescription: string;
  cta: string;
  generalKeyword: string;
  intent: string;
  market: string;
};

export const KEYWORD_H1_META_ROWS: readonly KeywordH1MetaRow[] = [
  {
    source: '/pmp-certification-uae',
    primaryKeyword: 'pmp certification uae',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Course: get live PMP training, exam prep, study resources, trainer support, fee guidance and a clear route to certification. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'UAE',
  },
  {
    source: '/online-pmp-course',
    primaryKeyword: 'online pmp course',
    h1: 'Online PMP Course',
    metaDescription: 'Online PMP Course: study live online with PMP exam prep, trainer support, study resources, flexible batches, fee guidance and WhatsApp enrollment. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'online pmp course',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-training-uae',
    primaryKeyword: 'pmp training uae',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: join live online PMP classes with exam prep, study resources, trainer support, fee guidance and fast WhatsApp enrollment. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'UAE',
  },
  {
    source: '/pmp-training-egypt',
    primaryKeyword: 'pmp training egypt',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: prepare for PMP with live classes, exam strategy, trainer guidance, study resources, batch details and enrollment support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Egypt',
  },
  {
    source: '/online-pmp-certification-course',
    primaryKeyword: 'online pmp certification course',
    h1: 'Online PMP Certification Course',
    metaDescription: 'Online PMP Certification Course: prepare for the PMP exam with live online classes, study resources, trainer support, batch details and enrollment help.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'online pmp certification course',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-saudi-arabia',
    primaryKeyword: 'pmp certification saudi arabia',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Training: build exam readiness with live online classes, PMI-focused prep, study support, course fee guidance and enrollment help. Learn more.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-certification-egypt',
    primaryKeyword: 'pmp certification egypt',
    h1: 'PMP Certification Training',
    metaDescription: 'Project Management Professional Certification: prepare for PMP with live classes, study resources, exam guidance, trainer support and course details. Start now.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Egypt',
  },
  {
    source: '/pmp-training-saudi-arabia',
    primaryKeyword: 'pmp training saudi arabia',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training: improve exam readiness with structured classes, PMP study resources, trainer support, mock practice and course fee guidance. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-course-saudi-arabia',
    primaryKeyword: 'pmp course saudi arabia',
    h1: 'PMP Course',
    metaDescription: 'PMP Course: prepare for PMP with live training, exam prep, study resources, trainer support, fee details and fast enrollment guidance. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp course',
    intent: 'Transactional',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-course-uae',
    primaryKeyword: 'pmp course uae',
    h1: 'PMP Course',
    metaDescription: 'PMP Course: learn the PMP framework with live classes, exam-focused support, study materials, trainer guidance and clear batch details. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp course',
    intent: 'Transactional',
    market: 'UAE',
  },
  {
    source: '/corporate-project-management-training',
    primaryKeyword: 'corporate project management training',
    h1: 'Corporate Project Management Training',
    metaDescription: 'Corporate Project Management Training: upskill teams in planning, delivery, risk, reporting and stakeholder management with live workshops. Start today.',
    cta: 'Book corporate training call',
    generalKeyword: 'corporate project management training',
    intent: 'B2B Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-training-qatar',
    primaryKeyword: 'pmp training qatar',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: join live online PMP classes with exam prep, study resources, trainer support, fee guidance and fast WhatsApp enrollment. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Qatar',
  },
  {
    source: '/project-management-training-for-companies',
    primaryKeyword: 'project management training for companies',
    h1: 'Project Management Training for Companies',
    metaDescription: 'Project Management Training for Companies: build team capability in planning, delivery, scheduling, risk and reporting through practical workshops. Start today.',
    cta: 'Book corporate training call',
    generalKeyword: 'project management training for companies',
    intent: 'B2B Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-qatar',
    primaryKeyword: 'pmp certification qatar',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Training: build exam readiness with live online classes, PMI-focused prep, study support, course fee guidance and enrollment help. Learn more.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Qatar',
  },
  {
    source: '/pmp-training-oman',
    primaryKeyword: 'pmp training oman',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: join live online PMP classes with exam prep, study resources, trainer support, fee guidance and fast WhatsApp enrollment. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Oman',
  },
  {
    source: '/corporate-pmp-training',
    primaryKeyword: 'corporate pmp training',
    h1: 'Corporate PMP Training',
    metaDescription: 'Corporate PMP Training: prepare teams for PMP with live classes, exam prep, trainer support, batch planning, reporting and enrollment guidance. Start today.',
    cta: 'Book corporate training call',
    generalKeyword: 'corporate pmp training',
    intent: 'B2B Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-oman',
    primaryKeyword: 'pmp certification oman',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Course: get live PMP training, exam prep, study resources, trainer support, fee guidance and a clear route to certification. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Oman',
  },
  {
    source: '/pmp-course-egypt',
    primaryKeyword: 'pmp course egypt',
    h1: 'PMP Course',
    metaDescription: 'PMP Course: prepare for PMP with live training, exam prep, study resources, trainer support, fee details and fast enrollment guidance. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp course',
    intent: 'Transactional',
    market: 'Egypt',
  },
  {
    source: '/pmp-exam-prep-course',
    primaryKeyword: 'pmp exam prep course',
    h1: 'PMP Exam Prep Course',
    metaDescription: 'PMP Exam Prep Course: prepare with live training, exam strategy, study resources, mock practice, trainer support and WhatsApp guidance from PM Structure.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp exam prep course',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-exam-preparation',
    primaryKeyword: 'pmp exam preparation',
    h1: 'PMP Exam Preparation',
    metaDescription: 'PMP Exam Preparation: build a clear study plan with live support, mock practice, exam strategy, resources and PMP trainer guidance from PM Structure. Start now.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp exam preparation',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-mock-exam',
    primaryKeyword: 'pmp mock exam',
    h1: 'PMP Mock Exam',
    metaDescription: 'PMP Mock Exam: practice realistic PMP questions, review weak areas, improve exam timing and get guidance for stronger PMP exam readiness. Start today.',
    cta: 'Download mock test / capture lead',
    generalKeyword: 'pmp mock exam',
    intent: 'Lead Magnet',
    market: 'GCC',
  },
  {
    source: '/pmp-practice-questions',
    primaryKeyword: 'pmp practice questions',
    h1: 'PMP Practice Questions',
    metaDescription: 'PMP Practice Questions: strengthen exam prep with scenario-based questions, answers, explanations, weak-area review and guided PMP study support. Start today.',
    cta: 'Download mock test / capture lead',
    generalKeyword: 'pmp practice questions',
    intent: 'Lead Magnet',
    market: 'GCC',
  },
  {
    source: '/project-management-course-egypt',
    primaryKeyword: 'project management course egypt',
    h1: 'Project Management Course',
    metaDescription: 'Project Management Course: build practical planning, scheduling, risk, stakeholder and delivery skills with live professional training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'project management course',
    intent: 'Transactional',
    market: 'Egypt',
  },
  {
    source: '/pmp-bootcamp',
    primaryKeyword: 'pmp bootcamp',
    h1: 'PMP Bootcamp',
    metaDescription: 'PMP Bootcamp: complete focused PMP exam prep through intensive live training, study resources, mock practice, trainer support and enrollment guidance.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp bootcamp',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-cost-egypt',
    primaryKeyword: 'pmp certification cost egypt',
    h1: 'PMP Certification Cost',
    metaDescription: 'PMP Certification Cost: compare PMP exam fees, course fees, training options, payment guidance and next steps before starting your PMP journey. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification cost',
    intent: 'Commercial Investigation',
    market: 'Egypt',
  },
  {
    source: '/pmp-certification-cost-uae',
    primaryKeyword: 'pmp certification cost uae',
    h1: 'PMP Certification Cost',
    metaDescription: 'PMP Certification Cost: compare PMP exam fees, course fees, training options, payment guidance and next steps before starting your PMP journey. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification cost',
    intent: 'Commercial Investigation',
    market: 'UAE',
  },
  {
    source: '/pmp-certification-online-egypt',
    primaryKeyword: 'pmp certification online egypt',
    h1: 'PMP Certification Online',
    metaDescription: 'PMP Certification Online: explore training details, live online classes, practical learning, trainer support, fees and enrollment guidance from PM Structure.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp certification online',
    intent: 'Transactional',
    market: 'Egypt',
  },
  {
    source: '/pmp-exam-fees-egypt',
    primaryKeyword: 'pmp exam fees egypt',
    h1: 'PMP Exam Fees',
    metaDescription: 'PMP Exam Fees: understand PMP exam costs, training fees, registration steps, study support and course guidance before you apply for PMP. Ask for details.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp exam fees',
    intent: 'Commercial Investigation',
    market: 'Egypt',
  },
  {
    source: '/pmp-certification-cost-saudi-arabia',
    primaryKeyword: 'pmp certification cost saudi arabia',
    h1: 'PMP Certification Cost',
    metaDescription: 'PMP Certification Cost: compare PMP exam fees, course fees, training options, payment guidance and next steps before starting your PMP journey. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification cost',
    intent: 'Commercial Investigation',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-exam-fees-uae',
    primaryKeyword: 'pmp exam fees uae',
    h1: 'PMP Exam Fees',
    metaDescription: 'PMP Exam Fees: understand PMP exam costs, training fees, registration steps, study support and course guidance before you apply for PMP. Ask for details.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp exam fees',
    intent: 'Commercial Investigation',
    market: 'UAE',
  },
  {
    source: '/pmp-exam-fees-saudi-arabia',
    primaryKeyword: 'pmp exam fees saudi arabia',
    h1: 'PMP Exam Fees',
    metaDescription: 'PMP Exam Fees: understand PMP exam costs, training fees, registration steps, study support and course guidance before you apply for PMP. Ask for details.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp exam fees',
    intent: 'Commercial Investigation',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-training-online-uae',
    primaryKeyword: 'pmp training online uae',
    h1: 'Online PMP Training',
    metaDescription: 'Online PMP Training: join live classes with PMP exam prep, study resources, trainer support, flexible batches, fee guidance and WhatsApp enrollment. Learn more.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training online',
    intent: 'Transactional',
    market: 'UAE',
  },
  {
    source: '/pmp-training-online-saudi-arabia',
    primaryKeyword: 'pmp training online saudi arabia',
    h1: 'Online PMP Training',
    metaDescription: 'Online PMP Training: join live classes with PMP exam prep, study resources, trainer support, flexible batches, fee guidance and WhatsApp enrollment. Learn more.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training online',
    intent: 'Transactional',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-course-fees-uae',
    primaryKeyword: 'pmp course fees uae',
    h1: 'PMP Course Fees',
    metaDescription: 'PMP Course Fees: review PMP training fees, live class options, exam prep support, study resources, payment guidance and WhatsApp enrollment. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp course fees',
    intent: 'Commercial Investigation',
    market: 'UAE',
  },
  {
    source: '/pmp-course-fees-in-saudi-arabia',
    primaryKeyword: 'pmp course fees in saudi arabia',
    h1: 'PMP Course Fees',
    metaDescription: 'PMP Course Fees: review PMP training fees, live class options, exam prep support, study resources, payment guidance and WhatsApp enrollment. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp course fees',
    intent: 'Commercial Investigation',
    market: 'Saudi Arabia',
  },
  {
    source: '/best-pmp-training-institute-uae',
    primaryKeyword: 'best pmp training institute uae',
    h1: 'Best PMP Training Institute',
    metaDescription: 'Best PMP Training Institute: compare PMP training quality, live classes, trainer support, exam prep, study resources, fees and enrollment guidance. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'best pmp training institute',
    intent: 'Commercial Investigation',
    market: 'UAE',
  },
  {
    source: '/pmp-certification-cost-qatar',
    primaryKeyword: 'pmp certification cost qatar',
    h1: 'PMP Certification Cost',
    metaDescription: 'PMP Certification Cost: compare PMP exam fees, course fees, training options, payment guidance and next steps before starting your PMP journey. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification cost',
    intent: 'Commercial Investigation',
    market: 'Qatar',
  },
  {
    source: '/how-to-get-pmp-certification',
    primaryKeyword: 'how to get pmp certification',
    h1: 'How to Get PMP Certification',
    metaDescription: 'How to Get PMP Certification: learn the PMP steps, eligibility, exam prep, application process, study plan, fees and training options. Ask for details.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'how to get pmp certification',
    intent: 'Informational',
    market: 'GCC',
  },
  {
    source: '/pmp-syllabus',
    primaryKeyword: 'pmp syllabus',
    h1: 'PMP Syllabus',
    metaDescription: 'PMP Syllabus: review PMP exam domains, topics, study areas, practice needs and course support to prepare with a structured learning plan. Start today.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp syllabus',
    intent: 'Informational',
    market: 'GCC',
  },
  {
    source: '/scrum-master-certification-training',
    primaryKeyword: 'scrum master certification training',
    h1: 'Scrum Master Certification Training',
    metaDescription: 'Scrum Master Certification Training: learn Scrum roles, agile practices, sprint planning, exam prep support and live training guidance. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'scrum master certification training',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/project-management-course-uae',
    primaryKeyword: 'project management course uae',
    h1: 'Project Management Course',
    metaDescription: 'Project Management Course: build practical planning, scheduling, risk, stakeholder and delivery skills with live professional training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'project management course',
    intent: 'Transactional',
    market: 'UAE',
  },
  {
    source: '/pmp-eligibility-requirements',
    primaryKeyword: 'pmp eligibility requirements',
    h1: 'PMP Eligibility Requirements',
    metaDescription: 'PMP Eligibility Requirements: understand PMP experience, education, contact hours, application steps and training support before applying. Start today.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp eligibility requirements',
    intent: 'Informational',
    market: 'GCC',
  },
  {
    source: '/pmp-study-plan',
    primaryKeyword: 'pmp study plan',
    h1: 'PMP Study Plan',
    metaDescription: 'PMP Study Plan: follow a structured PMP preparation roadmap with weekly study targets, practice questions, mock exams and trainer guidance. Start today.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp study plan',
    intent: 'Informational',
    market: 'GCC',
  },
  {
    source: '/primavera-p6-training',
    primaryKeyword: 'primavera p6 training',
    h1: 'Primavera P6 Training',
    metaDescription: 'Primavera P6 Training: learn project scheduling, baselines, resources, tracking and reporting with practical Primavera P6 training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'primavera p6 training',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/agile-project-management-course',
    primaryKeyword: 'agile project management course',
    h1: 'Project Management Course',
    metaDescription: 'Project Management Course: build practical planning, scheduling, risk, stakeholder and delivery skills with live professional training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'agile project management course',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/microsoft-project-training',
    primaryKeyword: 'microsoft project training',
    h1: 'Microsoft Project Training',
    metaDescription: 'Microsoft Project Training: learn task planning, timelines, resources, dependencies, tracking and reporting through practical MS Project training. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'microsoft project training',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-exam-dates-2026',
    primaryKeyword: 'pmp exam dates 2026',
    h1: 'PMP Exam Dates 2026',
    metaDescription: 'PMP Exam Dates 2026: understand PMP scheduling, exam windows, registration steps, prep timeline and training support for your exam plan. Ask for details.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp exam dates 2026',
    intent: 'Informational',
    market: 'GCC',
  },
  {
    source: '/risk-management-course',
    primaryKeyword: 'risk management course',
    h1: 'Risk Management Course',
    metaDescription: 'Risk Management Course: learn risk identification, analysis, response planning, controls and reporting with practical project risk training. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'risk management course',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-course-qatar',
    primaryKeyword: 'pmp course qatar',
    h1: 'PMP Course',
    metaDescription: 'PMP Course: learn the PMP framework with live classes, exam-focused support, study materials, trainer guidance and clear batch details. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp course',
    intent: 'Transactional',
    market: 'Qatar',
  },
  {
    source: '/pmp-for-project-managers',
    primaryKeyword: 'pmp for project managers',
    h1: 'PMP for Project Managers',
    metaDescription: 'PMP for Project Managers: upgrade project delivery skills with PMP exam prep, live classes, study resources, trainer guidance and course support. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp for project managers',
    intent: 'Commercial',
    market: 'GCC',
  },
  {
    source: '/pmp-renewal-pdu-courses',
    primaryKeyword: 'pmp renewal pdu courses',
    h1: 'PMP Renewal PDU Courses',
    metaDescription: 'PMP Renewal PDU Courses: earn PDUs, maintain your PMP credential and continue professional learning with practical project management courses. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp renewal pdu courses',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/project-management-certification-saudi-arabia',
    primaryKeyword: 'project management certification saudi arabia',
    h1: 'Project Management Certification',
    metaDescription: 'Project Management Certification: build recognized project management skills with training, exam guidance, study support and professional learning. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'project management certification',
    intent: 'Commercial',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-certification-requirements-uae',
    primaryKeyword: 'pmp certification requirements uae',
    h1: 'PMP Certification Requirements',
    metaDescription: 'PMP Certification Requirements: understand PMP eligibility, application steps, contact hours, exam prep and training support before applying. Start today.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp certification requirements',
    intent: 'Informational',
    market: 'UAE',
  },
  {
    source: '/pmp-course-oman',
    primaryKeyword: 'pmp course oman',
    h1: 'PMP Course',
    metaDescription: 'PMP Course: prepare for PMP with live training, exam prep, study resources, trainer support, fee details and fast enrollment guidance. Ask for details.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp course',
    intent: 'Transactional',
    market: 'Oman',
  },
  {
    source: '/pdu-courses-for-pmp',
    primaryKeyword: 'pdu courses for pmp',
    h1: 'PDU Courses for PMP',
    metaDescription: 'PDU Courses for PMP: earn PDUs through professional learning, project management topics, practical training support and credential renewal guidance. Learn more.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pdu courses for pmp',
    intent: 'Transactional',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-for-engineers',
    primaryKeyword: 'pmp certification for engineers',
    h1: 'PMP Certification for Engineers',
    metaDescription: 'PMP Certification for Engineers: prepare for PMP with project examples, exam prep, study resources, live classes and trainer-led guidance. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification for engineers',
    intent: 'Commercial',
    market: 'GCC',
  },
  {
    source: '/project-management-workshops',
    primaryKeyword: 'project management workshops',
    h1: 'Project Management Workshops',
    metaDescription: 'Project Management Workshops: train teams on planning, scheduling, risk, stakeholder management and delivery through practical workshop sessions. Start today.',
    cta: 'Book corporate training call',
    generalKeyword: 'project management workshops',
    intent: 'B2B Commercial',
    market: 'GCC',
  },
  {
    source: '/pmp-certification-kuwait',
    primaryKeyword: 'pmp certification kuwait',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Training: build exam readiness with live online classes, PMI-focused prep, study support, course fee guidance and enrollment help. Learn more.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Kuwait',
  },
  {
    source: '/pmp-certification-requirements-saudi-arabia',
    primaryKeyword: 'pmp certification requirements saudi arabia',
    h1: 'PMP Certification Requirements',
    metaDescription: 'PMP Certification Requirements: understand PMP eligibility, application steps, contact hours, exam prep and training support before applying. Start today.',
    cta: 'Read guide + CTA to course',
    generalKeyword: 'pmp certification requirements',
    intent: 'Informational',
    market: 'Saudi Arabia',
  },
  {
    source: '/pmp-classes-uae',
    primaryKeyword: 'pmp classes uae',
    h1: 'PMP Classes',
    metaDescription: 'PMP Classes: join live PMP training with exam prep, study resources, trainer support, flexible batches, fee guidance and enrollment help. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp classes',
    intent: 'Transactional',
    market: 'UAE',
  },
  {
    source: '/pmp-training-kuwait',
    primaryKeyword: 'pmp training kuwait',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: prepare for PMP with live classes, exam strategy, trainer guidance, study resources, batch details and enrollment support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Kuwait',
  },
  {
    source: '/project-management-course-qatar',
    primaryKeyword: 'project management course qatar',
    h1: 'Project Management Course',
    metaDescription: 'Project Management Course: build practical planning, scheduling, risk, stakeholder and delivery skills with live professional training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'project management course',
    intent: 'Transactional',
    market: 'Qatar',
  },
  {
    source: '/project-management-professional-certification-uae',
    primaryKeyword: 'project management professional certification uae',
    h1: 'Project Management Professional Certification',
    metaDescription: 'Project Management Professional Certification: prepare for PMP with live classes, study resources, exam guidance, trainer support and course details. Start now.',
    cta: 'Compare course + request fee',
    generalKeyword: 'project management professional certification',
    intent: 'Commercial',
    market: 'UAE',
  },
  {
    source: '/pmp-certification-bahrain',
    primaryKeyword: 'pmp certification bahrain',
    h1: 'PMP Certification Training',
    metaDescription: 'PMP Certification Training: prepare for the PMP exam with live classes, exam prep, trainer support, study resources, course fees and WhatsApp guidance.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification',
    intent: 'Commercial',
    market: 'Bahrain',
  },
  {
    source: '/pmp-certification-for-construction-professionals',
    primaryKeyword: 'pmp certification for construction professionals',
    h1: 'PMP Certification for Construction Professionals',
    metaDescription: 'PMP Certification for Construction Professionals: prepare for PMP with construction project examples, planning concepts, exam prep and trainer support.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification for construction professionals',
    intent: 'Commercial',
    market: 'GCC',
  },
  {
    source: '/pmp-training-bahrain',
    primaryKeyword: 'pmp training bahrain',
    h1: 'PMP Training Course',
    metaDescription: 'PMP Training Course: join live online PMP classes with exam prep, study resources, trainer support, fee guidance and fast WhatsApp enrollment. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'pmp training',
    intent: 'Transactional',
    market: 'Bahrain',
  },
  {
    source: '/project-management-course-oman',
    primaryKeyword: 'project management course oman',
    h1: 'Project Management Course',
    metaDescription: 'Project Management Course: build practical planning, scheduling, risk, stakeholder and delivery skills with live professional training support. Start today.',
    cta: 'Enroll / WhatsApp inquiry',
    generalKeyword: 'project management course',
    intent: 'Transactional',
    market: 'Oman',
  },
  {
    source: '/pmp-certification-cost-oman',
    primaryKeyword: 'pmp certification cost oman',
    h1: 'PMP Certification Cost',
    metaDescription: 'PMP Certification Cost: compare PMP exam fees, course fees, training options, payment guidance and next steps before starting your PMP journey. Start today.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp certification cost',
    intent: 'Commercial Investigation',
    market: 'Oman',
  },
  {
    source: '/pmp-exam-fees-qatar',
    primaryKeyword: 'pmp exam fees qatar',
    h1: 'PMP Exam Fees',
    metaDescription: 'PMP Exam Fees: understand PMP exam costs, training fees, registration steps, study support and course guidance before you apply for PMP. Ask for details.',
    cta: 'Compare course + request fee',
    generalKeyword: 'pmp exam fees',
    intent: 'Commercial Investigation',
    market: 'Qatar',
  },
  {
    source: '/all-courses',
    primaryKeyword: 'project management courses',
    h1: 'Project Management Courses',
    metaDescription: 'Project Management Courses: explore PMP, Agile, Primavera P6, risk management and Microsoft Project training with live classes and expert support. Start today.',
    cta: 'Explore courses + WhatsApp inquiry',
    generalKeyword: 'project management courses',
    intent: 'Commercial + Transactional',
    market: 'GCC / Global',
  }
] as const;

const BY_SOURCE = new Map(KEYWORD_H1_META_ROWS.map((row) => [row.source, row]));

export function getKeywordH1MetaBySource(path: string): KeywordH1MetaRow | undefined {
  if (!path) return undefined;
  const normalized = path.startsWith('/') ? path.replace(/\/+$/, '') || '/' : `/${path.replace(/\/+$/, '')}`;
  return BY_SOURCE.get(normalized);
}

export function getKeywordH1MetaByFromSlug(slug: string): KeywordH1MetaRow | undefined {
  const trimmed = slug.trim().replace(/^\/+|\/+$/g, '');
  if (!trimmed) return undefined;
  return BY_SOURCE.get(`/${trimmed}`);
}
