export {
  calendlyEventEnvVarName,
  getAllCalendlyEvents,
  getCalendlyCtaForChannelTier,
  getCalendlyManifestMeta,
  getCalendlyUrlForChannelTier,
  getEventBySlug,
  getEventForChannelTier,
  getPlatformFamilySlugPrefix,
  getWebsiteHeroConsultationEvent,
  getWebsiteHeroConsultationUrl,
  resolveCalendlyEventUrl,
  type CalendlyEvent,
  type CalendlyTierKind,
} from '@pms/booking-crm/calendly/event-registry';
