/**
 * Replace legacy "book/booking" mentor CTAs with mentor/advisor scheduling language.
 * Skips exam-provider context (Pearson VUE, handbooks, etc.).
 */

const EXACT_PHRASE_REPLACEMENTS: readonly (readonly [string, string])[] = [
  ['Official website consultation booking', 'Schedule advisory time on the website'],
  ['Publication-to-session booking', 'From publication to mentor call'],
  ['Facebook booking portal', 'Facebook mentor portal'],
  ['Answer-led booking', 'Answer-led mentor call'],
  ['VK community booking', 'VK community mentor calls'],
  ['Host-feed booking', 'Host-feed mentor sessions'],
  ['Workspace booking', 'Workspace mentor sessions'],
  ['Bing-intent booking', 'Bing-intent mentor call'],
  ['Feed subscriber booking', 'Feed subscriber mentor calls'],
  ['Syndicated API booking', 'Syndicated API mentor verification'],
  ['Server member advisory booking', 'Server member advisory sessions'],
  ['Search-intent advisory booking', 'Search-intent advisory sessions'],
  ['Inbox to booked advisory', 'Inbox to mentor advisory'],
  ['Turn reading into a booked block', 'Turn reading into a mentor session'],
  ['Book a free mentor intro or a paid pathway session', 'Schedule a free mentor intro or a paid pathway session'],
  ['book a free mentor intro or a paid pathway session', 'schedule a free mentor intro or a paid pathway session'],
  ['Book a free mentor intro', 'Talk to a mentor'],
  ['book a free mentor intro', 'talk to a mentor'],
  ['Book a mentor intro', 'Talk to a mentor'],
  ['book a mentor intro', 'talk to a mentor'],
  ['Book a session', 'Schedule a call with a mentor'],
  ['book a session', 'schedule a call with a mentor'],
  ['Book a call', 'Schedule a call with a mentor'],
  ['book a call', 'schedule a call with a mentor'],
  ['Book a consultation', 'Talk to an advisor'],
  ['book a consultation', 'talk to an advisor'],
  ['Book pathway session', 'Schedule a pathway session'],
  ['book pathway session', 'schedule a pathway session'],
  ['Book your session', 'Schedule your mentor call'],
  ['book your session', 'schedule your mentor call'],
  ['Book mentor time', 'Schedule mentor time'],
  ['book mentor time', 'schedule mentor time'],
  ['Book the live call', 'Schedule the live call'],
  ['Book from Notion', 'Schedule from Notion'],
  ['Book from VK', 'Schedule from VK'],
  ['Book from Bing', 'Schedule from Bing'],
  ['Book from the feed', 'Schedule from the feed'],
  ['Book from your pin', 'Schedule from your pin'],
  ['Book thread time', 'Schedule thread time'],
  ['Book on WhatsApp', 'Talk on WhatsApp'],
  ['Reply & book', 'Reply and schedule'],
  ['Snap-to-book', 'Snap to mentor call'],
  ['Fediverse booking', 'Fediverse mentor call'],
  ['Real-time booking', 'Real-time mentor scheduling'],
  ['Secure calendar booking', 'Secure calendar scheduling'],
  ['Secure booking', 'Secure scheduling'],
  ['Mentor booking', 'Mentor sessions'],
  ['mentor booking', 'mentor sessions'],
  ['booking portal', 'mentor portal'],
  ['Booking portal', 'Mentor portal'],
  ['booking note', 'session note'],
  ['Booking note', 'Session note'],
  ['Booking assurances', 'Scheduling assurances'],
  ['booking assurances', 'scheduling assurances'],
  ['Prep, pricing & booking', 'Prep, pricing & mentor calls'],
  ['Review before booking', 'Review before you schedule'],
  ['Why learners book from here', 'Why learners schedule mentor time here'],
  ['Why learners book here', 'Why learners schedule mentor time here'],
  ['Watch before you book', 'Watch before you schedule'],
  ['Booking and site shortcuts', 'Mentor calls and site shortcuts'],
  ['Booking request via', 'Mentor call request via'],
  ['Portal booking:', 'Portal mentor call:'],
  ['booked block', 'mentor session'],
  ['booked advisory', 'advisory session'],
  ['Booked from', 'Scheduled from'],
  ['booked from', 'scheduled from'],
  ['prompted this booking', 'prompted this mentor call'],
  ['this booking', 'this mentor call'],
  ['Host-feed bookings', 'Host-feed mentor sessions'],
  ['Channel booking open', 'Channel mentor calls open'],
  ['when you book', 'when you schedule'],
  ['When you book', 'When you schedule'],
  ['before you book', 'before you schedule'],
  ['Before you book', 'Before you schedule'],
  ['Didn\'t book a time?', 'Didn\'t schedule a time?'],
  ['Book a mentor call later', 'Schedule a mentor call later'],
  ['portal booking request', 'portal mentor call request'],
  ['Book after your', 'Schedule after your'],
  ['Book after watching', 'Schedule after watching'],
  ['Book after the', 'Schedule after the'],
  ['Book depth', 'Schedule depth'],
  ['Book rigor', 'Schedule rigor'],
  ['Book principal', 'Schedule principal'],
  ['Book with context', 'Schedule with context'],
  ['Book from feed', 'Schedule from feed'],
  ['Book from', 'Schedule from'],
  ['Book an academic', 'Schedule an academic'],
  ['Book time', 'Schedule time'],
  ['Book advisory', 'Schedule advisory'],
  ['Book human', 'Schedule human'],
  ['Book your', 'Schedule your'],
  ['Book a focused', 'Schedule a focused'],
  ['Book a strategy', 'Schedule a strategy'],
  ['Book a longer', 'Schedule a longer'],
  ['Book a mentor', 'Talk to a mentor'],
  ['book a mentor', 'talk to a mentor'],
  [' — Book a session', ' — Schedule a mentor call'],
  [' - Book a session', ' - Schedule a mentor call'],
  ['Inbox CTA to booked block', 'Inbox CTA to mentor session'],
  ['learners book after', 'learners schedule after'],
  ['Learners book after', 'Learners schedule after'],
  ['Site visitors book', 'Site visitors schedule'],
  ['site visitors book', 'site visitors schedule'],
  ['You want to book', 'You want to schedule'],
  ['you want to book', 'you want to schedule'],
  ['Reserve a focused advisory block. Cite what brought you here when you book.', 'Reserve a focused advisory block. Cite what brought you here when you schedule.'],
]

const SKIP_SUBSTRINGS = [
  'pearson vue',
  'handbook',
  'booking_form',
  'meeting_booking',
  'booking_modal',
  'booking_step',
  'booking_confirmed',
  'booking-flow',
  'booking-sh3ik',
  'exam booking',
  'official exam booking',
]

function shouldSkipLexicon(text: string): boolean {
  const lower = text.toLowerCase()
  return SKIP_SUBSTRINGS.some((s) => lower.includes(s))
}

export function applyMentorCtaLexicon(text: string): string {
  if (!text?.trim() || shouldSkipLexicon(text)) return text

  let result = text
  for (const [from, to] of EXACT_PHRASE_REPLACEMENTS) {
    if (result.includes(from)) {
      result = result.split(from).join(to)
    }
  }
  return result
}
