export type BrandSourceConfidence = 'official-guideline' | 'official-product-ui' | 'fallback'

export type BrandPullability = 'yes' | 'partial' | 'no'

export type PlatformBrandSource = {
  channelId: string
  label: string
  primarySourceUrl: string
  secondarySourceUrl?: string
  iconSourceUrl?: string
  sourceConfidence: BrandSourceConfidence
  themePullability: BrandPullability
  iconPullability: BrandPullability
  fontPullability: BrandPullability
  notes?: string
}

/**
 * Current implementation scope is 41 slugs.
 * google-podcasts is excluded as a legacy/deprecated channel.
 */
export const EXCLUDED_CHANNEL_ID = 'google-podcasts'

export const IMPLEMENTATION_SCOPE_41: string[] = [
  'website',
  'webinar',
  'medium',
  'substack',
  'beehiiv',
  'ghost',
  'hashnode',
  'notion-public',
  'linkedin',
  'twitter',
  'instagram',
  'facebook',
  'reddit',
  'threads',
  'quora',
  'bluesky',
  'mastodon',
  'pinterest',
  'vk',
  'youtube',
  'tiktok',
  'snapchat',
  'vimeo',
  'spotify',
  'apple-podcasts',
  'amazon-audible',
  'podbean',
  'soundcloud',
  'email',
  'whatsapp',
  'telegram',
  'discord',
  'slack',
  'google-search',
  'youtube-search',
  'podcast-directories',
  'bing-search',
  'ai-visibility',
  'rss-feeds',
  'content-aggregators',
  'api-ai-fed',
]

export const PLATFORM_BRAND_SOURCES: Record<string, PlatformBrandSource> = {
  website: {
    channelId: 'website',
    label: 'Website',
    primarySourceUrl: 'https://www.apple.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
    notes: 'Owned platform style benchmark.',
  },
  webinar: {
    channelId: 'webinar',
    label: 'Webinar',
    primarySourceUrl: 'https://www.youtube.com',
    sourceConfidence: 'fallback',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
    notes: 'Internal channel; no single external brand.',
  },
  medium: {
    channelId: 'medium',
    label: 'Medium',
    primarySourceUrl: 'https://brand.medium.com',
    secondarySourceUrl: 'https://www.medium.com',
    iconSourceUrl: 'https://brand.medium.com',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'yes',
  },
  substack: {
    channelId: 'substack',
    label: 'Substack',
    primarySourceUrl: 'https://substack.com',
    secondarySourceUrl: 'https://on.substack.com',
    iconSourceUrl: 'https://substack.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  beehiiv: {
    channelId: 'beehiiv',
    label: 'Beehiiv',
    primarySourceUrl: 'https://www.beehiiv.com',
    secondarySourceUrl: 'https://blog.beehiiv.com',
    iconSourceUrl: 'https://www.beehiiv.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  ghost: {
    channelId: 'ghost',
    label: 'Ghost',
    primarySourceUrl: 'https://ghost.org/brand/',
    secondarySourceUrl: 'https://ghost.org',
    iconSourceUrl: 'https://ghost.org/brand/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  hashnode: {
    channelId: 'hashnode',
    label: 'Hashnode',
    primarySourceUrl: 'https://hashnode.com',
    secondarySourceUrl: 'https://support.hashnode.com',
    iconSourceUrl: 'https://hashnode.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  'notion-public': {
    channelId: 'notion-public',
    label: 'Notion',
    primarySourceUrl: 'https://www.notion.so/brand',
    secondarySourceUrl: 'https://www.notion.so',
    iconSourceUrl: 'https://www.notion.so/brand',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  linkedin: {
    channelId: 'linkedin',
    label: 'LinkedIn',
    primarySourceUrl: 'https://brand.linkedin.com',
    secondarySourceUrl: 'https://www.linkedin.com',
    iconSourceUrl: 'https://brand.linkedin.com',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'yes',
  },
  twitter: {
    channelId: 'twitter',
    label: 'X',
    primarySourceUrl: 'https://about.x.com/en/who-we-are/brand-toolkit',
    secondarySourceUrl: 'https://x.com',
    iconSourceUrl: 'https://about.x.com/en/who-we-are/brand-toolkit',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  instagram: {
    channelId: 'instagram',
    label: 'Instagram',
    primarySourceUrl: 'https://about.meta.com/brand/resources/instagram/',
    secondarySourceUrl: 'https://www.instagram.com',
    iconSourceUrl: 'https://about.meta.com/brand/resources/instagram/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  facebook: {
    channelId: 'facebook',
    label: 'Facebook',
    primarySourceUrl: 'https://about.meta.com/brand/resources/facebook/',
    secondarySourceUrl: 'https://www.facebook.com',
    iconSourceUrl: 'https://about.meta.com/brand/resources/facebook/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  reddit: {
    channelId: 'reddit',
    label: 'Reddit',
    primarySourceUrl: 'https://redditinc.com/brand',
    secondarySourceUrl: 'https://www.reddit.com',
    iconSourceUrl: 'https://redditinc.com/brand',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  threads: {
    channelId: 'threads',
    label: 'Threads',
    primarySourceUrl: 'https://about.meta.com/brand/resources/threads/',
    secondarySourceUrl: 'https://www.threads.net',
    iconSourceUrl: 'https://about.meta.com/brand/resources/threads/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  quora: {
    channelId: 'quora',
    label: 'Quora',
    primarySourceUrl: 'https://www.quora.com',
    secondarySourceUrl: 'https://www.quora.com/about',
    iconSourceUrl: 'https://www.quora.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  bluesky: {
    channelId: 'bluesky',
    label: 'Bluesky',
    primarySourceUrl: 'https://bsky.app',
    iconSourceUrl: 'https://bsky.app',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  mastodon: {
    channelId: 'mastodon',
    label: 'Mastodon',
    primarySourceUrl: 'https://joinmastodon.org/branding',
    secondarySourceUrl: 'https://joinmastodon.org',
    iconSourceUrl: 'https://joinmastodon.org/branding',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  pinterest: {
    channelId: 'pinterest',
    label: 'Pinterest',
    primarySourceUrl: 'https://business.pinterest.com/brand-guidelines/',
    secondarySourceUrl: 'https://www.pinterest.com',
    iconSourceUrl: 'https://business.pinterest.com/brand-guidelines/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  vk: {
    channelId: 'vk',
    label: 'VK',
    primarySourceUrl: 'https://vk.com/brand',
    secondarySourceUrl: 'https://vk.com',
    iconSourceUrl: 'https://vk.com/brand',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  youtube: {
    channelId: 'youtube',
    label: 'YouTube',
    primarySourceUrl: 'https://www.youtube.com/howyoutubeworks/resources/brand-resources/',
    secondarySourceUrl: 'https://www.youtube.com',
    iconSourceUrl: 'https://www.youtube.com/howyoutubeworks/resources/brand-resources/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'yes',
  },
  tiktok: {
    channelId: 'tiktok',
    label: 'TikTok',
    primarySourceUrl: 'https://www.tiktok.com',
    secondarySourceUrl: 'https://www.tiktok.com/about',
    iconSourceUrl: 'https://www.tiktok.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  snapchat: {
    channelId: 'snapchat',
    label: 'Snapchat',
    primarySourceUrl: 'https://kit.snapchat.com/brand-guidelines',
    secondarySourceUrl: 'https://www.snapchat.com',
    iconSourceUrl: 'https://kit.snapchat.com/brand-guidelines',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  vimeo: {
    channelId: 'vimeo',
    label: 'Vimeo',
    primarySourceUrl: 'https://vimeo.com/brand_guidelines',
    secondarySourceUrl: 'https://vimeo.com',
    iconSourceUrl: 'https://vimeo.com/brand_guidelines',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  spotify: {
    channelId: 'spotify',
    label: 'Spotify',
    primarySourceUrl: 'https://developer.spotify.com/branding-guidelines',
    secondarySourceUrl: 'https://open.spotify.com',
    iconSourceUrl: 'https://developer.spotify.com/branding-guidelines',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  'apple-podcasts': {
    channelId: 'apple-podcasts',
    label: 'Apple Podcasts',
    primarySourceUrl:
      'https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html',
    secondarySourceUrl: 'https://podcasts.apple.com',
    iconSourceUrl:
      'https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  'amazon-audible': {
    channelId: 'amazon-audible',
    label: 'Amazon Music / Audible',
    primarySourceUrl: 'https://www.audible.com',
    secondarySourceUrl: 'https://music.amazon.com',
    iconSourceUrl: 'https://www.audible.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  podbean: {
    channelId: 'podbean',
    label: 'Podbean',
    primarySourceUrl: 'https://www.podbean.com',
    secondarySourceUrl: 'https://www.podbean.com/site/brand',
    iconSourceUrl: 'https://www.podbean.com',
    sourceConfidence: 'official-product-ui',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  soundcloud: {
    channelId: 'soundcloud',
    label: 'SoundCloud',
    primarySourceUrl: 'https://soundcloud.com/pages/brand-assets',
    secondarySourceUrl: 'https://soundcloud.com',
    iconSourceUrl: 'https://soundcloud.com/pages/brand-assets',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  email: {
    channelId: 'email',
    label: 'Email',
    primarySourceUrl: 'https://mail.google.com',
    sourceConfidence: 'fallback',
    themePullability: 'no',
    iconPullability: 'no',
    fontPullability: 'no',
    notes: 'Internal channel without single canonical public brand.',
  },
  whatsapp: {
    channelId: 'whatsapp',
    label: 'WhatsApp Channels',
    primarySourceUrl: 'https://about.meta.com/brand/resources/whatsapp/',
    secondarySourceUrl: 'https://www.whatsapp.com',
    iconSourceUrl: 'https://about.meta.com/brand/resources/whatsapp/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  telegram: {
    channelId: 'telegram',
    label: 'Telegram',
    primarySourceUrl: 'https://telegram.org/brand',
    secondarySourceUrl: 'https://telegram.org',
    iconSourceUrl: 'https://telegram.org/brand',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  discord: {
    channelId: 'discord',
    label: 'Discord',
    primarySourceUrl: 'https://discord.com/branding',
    secondarySourceUrl: 'https://discord.com',
    iconSourceUrl: 'https://discord.com/branding',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  slack: {
    channelId: 'slack',
    label: 'Slack',
    primarySourceUrl: 'https://slack.com/brand-guidelines',
    secondarySourceUrl: 'https://slack.com',
    iconSourceUrl: 'https://slack.com/brand-guidelines',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'yes',
    fontPullability: 'partial',
  },
  'google-search': {
    channelId: 'google-search',
    label: 'Google Search',
    primarySourceUrl: 'https://about.google/brand-resource-center/',
    secondarySourceUrl: 'https://www.google.com',
    iconSourceUrl: 'https://about.google/brand-resource-center/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  'youtube-search': {
    channelId: 'youtube-search',
    label: 'YouTube Search',
    primarySourceUrl: 'https://www.youtube.com/howyoutubeworks/resources/brand-resources/',
    secondarySourceUrl: 'https://www.youtube.com/results',
    iconSourceUrl: 'https://www.youtube.com/howyoutubeworks/resources/brand-resources/',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  'podcast-directories': {
    channelId: 'podcast-directories',
    label: 'Podcast Directories',
    primarySourceUrl: 'https://podcasts.apple.com',
    sourceConfidence: 'fallback',
    themePullability: 'partial',
    iconPullability: 'partial',
    fontPullability: 'partial',
    notes: 'Aggregator category; multiple external brands.',
  },
  'bing-search': {
    channelId: 'bing-search',
    label: 'Bing Search',
    primarySourceUrl:
      'https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks',
    secondarySourceUrl: 'https://www.bing.com',
    iconSourceUrl:
      'https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks',
    sourceConfidence: 'official-guideline',
    themePullability: 'yes',
    iconPullability: 'partial',
    fontPullability: 'partial',
  },
  'ai-visibility': {
    channelId: 'ai-visibility',
    label: 'AI Visibility',
    primarySourceUrl: 'https://openai.com/brand',
    sourceConfidence: 'fallback',
    themePullability: 'no',
    iconPullability: 'no',
    fontPullability: 'no',
    notes: 'Internal composite channel; no single external brand.',
  },
  'rss-feeds': {
    channelId: 'rss-feeds',
    label: 'RSS Feeds',
    primarySourceUrl: 'https://www.rssboard.org/rss-specification',
    sourceConfidence: 'fallback',
    themePullability: 'partial',
    iconPullability: 'partial',
    fontPullability: 'no',
    notes: 'Protocol channel; no canonical platform font.',
  },
  'content-aggregators': {
    channelId: 'content-aggregators',
    label: 'Content Aggregators',
    primarySourceUrl: 'https://feedly.com',
    sourceConfidence: 'fallback',
    themePullability: 'no',
    iconPullability: 'no',
    fontPullability: 'no',
    notes: 'Internal composite channel; no single external brand.',
  },
  'api-ai-fed': {
    channelId: 'api-ai-fed',
    label: 'API / AI-fed Systems',
    primarySourceUrl: 'https://openai.com/api',
    sourceConfidence: 'fallback',
    themePullability: 'no',
    iconPullability: 'no',
    fontPullability: 'no',
    notes: 'Internal integration channel; no single external brand.',
  },
}

