/** Per-channel tier intro line (shown under “Pick a session” / “Select consultation tier”). */
export const TIER_SCHEDULING_LINES: Record<string, string> = {
  webinar:
    'Free mentor intro or paid pathway session. Cite the webinar title or replay in your booking note.',
  website:
    'Book mentor time for certification fit and prep. Cite the site page or asset when you reserve.',
  medium: 'Turn the Medium piece into mentor prep time. Reference the article in your note.',
  substack:
    'Continue the newsletter thread in a live block. Cite the post or issue when you book.',
  beehiiv: 'Move from inbox to mentor time. Align publication cadence with your prep schedule.',
  ghost: 'Go beyond the post. Align publication themes with your certification goal.',
  hashnode: 'Connect what you read to exam prep. Link the article when you book.',
  'notion-public': 'Translate docs into a study plan. Name the Notion page or view in your booking note.',
  linkedin: 'Executive pathway fit and sponsor-ready next steps. Reference your LinkedIn context when you book.',
  twitter: 'Expand a thread into structured guidance. Drop the post URL or topic in your note.',
  instagram: 'Lock discovery or deep-dive time. Name the reel, story, or post when you reserve.',
  facebook: 'Book from feed or group context. Share which post or group applies.',
  reddit: 'Move from thread debate to a mentor call. Link the subreddit thread you came from.',
  threads: 'Continue from Threads without losing context. Mention the post that prompted this booking.',
  quora: 'Deepen the answer into structured prep guidance. Cite the Quora question or answer URL.',
  bluesky: 'Book a focused block from the open network. Mention the post or thread that referred you.',
  mastodon: 'Fediverse referral to mentor time. Include your instance and the referring post.',
  pinterest: 'Align visual research with certification choices. Note which pin or board led you here.',
  youtube: 'Go deeper than the video. Name the channel video or series when you reserve.',
  tiktok: 'Book rigor the clip cannot hold. Drop the TikTok link or hook in your booking note.',
  snapchat: 'Reserve fast without leaving the flow. Tell us which Snap or story you came from.',
  vimeo: 'Professional showcase to mentor depth. Reference the Vimeo title you watched.',
  spotify: 'Translate the episode into a pathway plan. Name the episode when you book.',
  'apple-podcasts': 'Listener depth after Apple Podcasts. Cite the show or episode in your note.',
  'amazon-audible': 'Audible listener follow-up. Which title or episode referred you?',
  'google-podcasts': 'Feed discovery to mentor time. Share the episode link if you have it.',
  podbean: 'Host-feed listeners. Reference the Podbean episode when you reserve.',
  soundcloud: 'From stream to structured guidance. Link the track or playlist you came from.',
  email: 'Inbox CTA to booked block. Note the email subject or campaign in your booking note.',
  whatsapp: 'Channel broadcast to calendar. Mention the message or broadcast you saw.',
  telegram: 'Telegram channel to mentor time. Which channel post referred you?',
  discord: 'Server or thread referral. Name the channel or thread that linked you here.',
  slack: 'Workspace referral with context intact. Which channel or workspace prompted this?',
  'google-search': 'Honor search intent. State the query or result that brought you here.',
  'youtube-search': 'YouTube SERP to live session. Which search result did you click?',
  'podcast-directories': 'Directory discovery to mentor time. Which listing referred you?',
  'bing-search': 'Bing search to qualified call. Share the query or snippet that matched your need.',
  'ai-visibility': 'Verify AI-surfaced fit in a human block. Note the prompt or surface if known.',
  'rss-feeds': 'Syndicated feed to mentor time. Cite the feed item or enclosure you read.',
  'content-aggregators': 'Aggregator bundle to mentor session. Name the bundle or source that linked you.',
  'api-ai-fed': 'Machine-surfaced referral. Book human verification; name the API consumer if known.',
}
